### ISSUE TITLE
Strict validation vs ignore invalid targets (--strict flag)

### ISSUE THREAD

**Issue by extremewaysback** [cosminbasca/cleanmymac#1]
OS X: 10.11.3
run $cleanmymac
## get the following errors

cleaning: MACTEX
Traceback (most recent call last):
  File "/Users/Extremeways/Library/Enthought/Canopy_64bit/User/bin/cleanmymac", line 11, in <module>
    sys.exit(run_cmd())
  File "/Users/Extremeways/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cleanmymac/cli.py", line 145, in run_cmd
    target = target_initializer(target_cfg, update=update, verbose=verbose)
  File "/Users/Extremeways/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cleanmymac/registry.py", line 51, in load_target
    description = validate_yaml_target(description)
  File "/Users/Extremeways/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cleanmymac/schema.py", line 121, in validate_yaml_target
    description['spec'] = **TYPE_SCHEMA**[_type](_spec)
  File "/Users/Extremeways/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/voluptuous.py", line 337, in **call**
    return self._compiled([], data)
  File "/Users/Extremeways/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/voluptuous.py", line 635, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/Users/Extremeways/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/voluptuous.py", line 471, in validate_mapping
    raise MultipleInvalid(errors)

**Comment by cosminbasca** [comment]
Hi, the error means that the folder specified in mactex.yaml is not a valid directory on your system (i.e., does not exist). The default value is: **/usr/local/texlive/**. The validator will check if the folder exists before proceeding. It is a good idea to add a --strict flag which would enforce the strict compliance to the schema and have it off by default. In that case the utility will display a warning message when the folder is not found, and not execute the invalid target.

In the mean time, you can just call the utility for targets that make sense for your system (by specifying them in the cli). I will create an issue for the "strict" mode.

**Comment by extremewaysback** [comment]
@cosminbasca Thanks!

**Comment by cosminbasca** [comment]
ok, I've added the flag --strict/--no-strict to the command line. By default strict mode is on. So in order to run without it just add --no-strict. Latest version is 0.1.12 now available on pypi. 

Please let me know if your run into more errors. 

Cheers,
Cosmin
