### ISSUE TITLE
Getting some errors

### ISSUE THREAD

**Issue by phi-line** [cosminbasca/cleanmymac#2]
```
Traceback (most recent call last):
  File "/usr/local/bin/cleanmymac", line 11, in <module>
    load_entry_point('cleanmymac==0.1.17', 'console_scripts', 'cleanmymac')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/cleanmymac-0.1.17-py3.6.egg/cleanmymac/cli.py", line 180
    except Exception, ex:
                    ^
SyntaxError: invalid syntax
```

and upon fixing that one:
```
Traceback (most recent call last):
  File "/usr/local/bin/cleanmymac", line 11, in <module>
    load_entry_point('cleanmymac==0.1.17', 'console_scripts', 'cleanmymac')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/cleanmymac-0.1.17-py3.6.egg/cleanmymac/cli.py", line 77, in <module>
    @click_log.init()
AttributeError: module 'click_log' has no attribute 'init'
```

**Comment by tlan16** [comment]
I got a similar error here.
```
➜  /tmp cleanmymac           
Traceback (most recent call last):
  File "/usr/local/bin/cleanmymac", line 7, in <module>
    from cleanmymac.cli import cli
  File "/usr/local/lib/python3.6/site-packages/cleanmymac/cli.py", line 173
    except Exception, ex:
                    ^
SyntaxError: invalid syntax
```

**Comment by phi-line** [comment]
you need to make sure that your Python environment export references Python 2 instead of 3.

```
In Python 3.x, using as is required to assign an exception to a variable.
In Python 2.6+, use the as syntax, since it is far less ambiguous and forward compatible with Python 3.x.
In Python 2.5 and earlier, use the comma version, since as isn't supported.
```
[Source](https://stackoverflow.com/questions/2535760/python-try-except-comma-vs-as-in-except)
